[package]
name = "suplex"
version = "0.1.0"
edition = "2024"
license = "MIT OR Apache-2.0"
authors = ["Graham Keenan <graham.keenan@outlook.com>"]
repository = "https://github.com/Tyrannican/suplex"
homepage = "https://github.com/Tyrannican/suplex"
description = "Request-Response wrapper over Crossbeam channels"
keywords = ["channel", "mpmc", "crossbeam", "message"]
categories = ["algorithms", "concurrency", "data-structures"]
readme = "README.md"

[dependencies]
crossbeam-channel = "0.5.15"
